version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    networks:
      - kafka_network

  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093
      KAFKA_LISTENER_NAME_SELECTOR: INSIDE
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - kafka_network

  reports:
    image: reports
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - postgres
      - redis
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9093
    networks:
      - kafka_network

  generating_microservice:
    image: generating_microservice
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9093
    depends_on:
      - kafka
      - reports
    networks:
      - kafka_network

  redis:
    image: redis:latest
    command: ["redis-server", "--requirepass", "1234"]
    ports:
      - "6379:6379"
    networks:
      - kafka_network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - kafka_network

networks:
  kafka_network:

